import os
filename=input("enter file name you want create:")
if os.path.exists(filename+".txt"):
  os.remove(filename+".txt")
f = open(filename+".txt", "a")
name=input("enter you name")
mobile=input("enter your phone number")
address=input("enter address")
#f.write(name)
#f.write("Name:"+name+",phone:"+mobile+",address:"+address)
f.write("Name:"+name+"\n")
f.write("phone:"+mobile+"\n")
f.write("address:"+address+"\n")
#"\n phone:", mobile,"\n address:" , address)
f = open(filename+".txt", "r")
print("Please check your entered data")
print(f.read())
#print(f.read())
f.close()
